---
layout: post
title:  The value of lead time
date: 2017-06-16
published: yes
comments: yes
tags: [lead time, operations, forecast evolution, option pricing]
---

In [two very nice papers](#references), Suzanne and her collaborators developped 
an interesting idea about valuing lead time based on financial mathematics related 
to option pricing. In the [standard newsvendor model](https://en.wikipedia.org/wiki/Newsvendor_model), the profits of the firm at delivery time $$T$$ for an order of $$Q$$ units are

\\[
\begin{align}
\Pi_T &= p \min(D_T,Q) - c Q + s \max(Q-D_T, 0) \\\
&= (p-c) Q - (p-s) \max(Q-D_T, 0),
\end{align}
\\]

where $$D_T$$ is the demand, $$p$$ is the selling price of the product, $$c$$ its cost and $$s$$ its salvage value. The usual solution, i.e. the profit-maximizing order quantity is given by $$Q = F^{-1}(\alpha)$$,
where $$F$$ is the distribution of the unkown demand, $$\alpha = (p-c)/(p-s)$$.

Looking closer at the profits, one recognizes in $$\max(Q-D_T, 0)$$ the payoff of a put 
option on the demand with strike $$Q$$. Under absence of arbitrage, the $$t \leq T$$ price of such an option is $$P(D_t,t,T,Q) = E^{\mathcal{Q}}_t \left[ \max(Q-D_T, 0) \right]$$, where $$\mathcal{Q}$$ denotes the risk-neutral probability measure, and thus the expected profit can be written as

\\[
 E^{\mathcal{Q}}_t \left[ \Pi_T \right] = (p-c) Q - (p-s) P(D_t,t,T,Q).
\\]

Let us assume that the firm as the choice between

* producing at $$t_s \leq  T$$ for a cost $$c_s$$,
* producing at $$t_l< t_s$$ for a cost $$c_l < c_s$$.

This is typical of a situation when a firm can choose between a local production or a delocalization. Now, the interesting question is: how can we value lead time? In other words, what are the right $$c_l$$ and $$c_s$$ to compensate the firm for the uncertainty about future demand? Or given $$c_l$$, which $$c_s$$ would the firm require to be indifferent between producing at $$t_s$$ and $$t_l$$?

For the sake of simplicity, we will fix $$t_s = T$$ (i.e., $$c_s$$ is the make-to-order cost), $$t_l=0$$ and $$D_0=1$$. Given $$c_l$$, let $$Q_l$$ denote the profit maximizing order quantity. If the distribution of the demand is known, then $$Q_l$$ can be computed as for the newsvendor model. Otherwise, one has to numerically solve
\\[
 Q_l = \mbox{argmax}_Q \left\lbrace (p-c_l) Q - (p-s) P(1,0,T,Q) \right\rbrace.
\\]

In the make-to-order case, it is clear that $$Q_s=D_T$$. Since, under the absence of arbitrage, we have 
$$E^{\mathcal{Q}}_t \left[ D_T \right] = D_t$$, it follows that the expected profit at time $$0$$ is simply $$p-c_s$$. 
As such, the cost $$c_s$$ making the firm indifferent between producing at time $$0$$ or time $$T$$ is given by

\\[
c_s = p - (p-c_l) Q_l + (p-s) P(1,0,T,Q_l).
\\]

In the [shiny app](https://shiny.rstudio.com/) below (see [https://tvatter.shinyapps.io/shinycdf/](https://tvatter.shinyapps.io/shinycdf/) for the full screen version), we assume that $$T=1$$ and show the cost differential frontier, namely $$(c_s-c_l)/c_s$$ as a function of $$t_l \in [0,T]$$:

<iframe src="https://tvatter.shinyapps.io/shinycdf/" width="100%" height="600" style="border: none;"></iframe>

## References

de Treville, S., Schürhoff, N., Trigeorgis, L. and Avanzi, B. (2014)  
[Optimal Sourcing and Lead-Time Reduction under Evolutionary Demand  Risk](http://dx.doi.org/10.1111/poms.12223)  
*Production and Operations Management, Volume 23, Issue 12, 2103-2117*

de Treville, S., Bicer, I., Chavez-Demoulin, V., Hagspiel, V., Schürhoff, N., Tasserit, C. and Wager, S. (2014)  
[Valuing lead time](http://dx.doi.org/10.1016/j.jom.2014.06.002)  
*Journal of Operations Management, Volume 32, Issue 6, 337-346*